name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    types: [ opened, synchronize, reopened, labeled, unlabeled, review_requested, review_dismissed, edited ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

    - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install aspire workload
        run: dotnet workload install aspire

      - name: Restore dependencies
        run: dotnet restore

      - name: Configure build configuration
        run: dotnet buildconfig -c Release

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal